feat: Add logger to log message
DLTcollab/TA-endpoint pull request #42
Opened 2020-03-17 07:46 UTC by splasky

Logger is helpful for generate debug message or info. It can also
disable all debug message when DEBUG flag not set.

2020-03-17 14:14 UTC, jserv commented
It is redundant to denote "Add logger to log message." Logger is always used for logging. Instead, you have to explain how the logger works along with potential integration efforts.

2020-03-17 14:14 UTC, jserv commented
Add documentation!

2020-03-17 17:01 UTC, splasky commented
related #34

2020-03-17 17:03 UTC, jserv commented
Fix conflicts.

2020-03-17 17:07 UTC, jserv requested changes
"preparation" should be emphasized since no code snippet is using logger so far.

2020-03-17 17:24 UTC, jserv commented on utils/logger.c
> +static int TA_LOG_LEVEL = LV_INFO;
You should implement non-trivial logger, which takes circular buffer into consideration.

2020-03-20 03:10 UTC, jserv commented on utils/logger.h
> +
Add comments about these level.

2020-04-28 08:49 UTC, splasky commented
Will use the tangle-accelerator's logger as default logger.

2020-04-28 08:49 UTC, closed without merging