fix: Fix warning during compiling
DLTcollab/TA-endpoint pull request #44
Opened 2020-03-17 08:29 UTC by splasky

Fix duplicate `const` declaration specifier warning.

2020-03-17 10:35 UTC, howjmay approved these changes

2020-03-17 14:11 UTC, jserv requested changes
I have tweaked the subject of this pull request. Make it informative.

2020-03-17 14:15 UTC, howjmay requested changes
typo `duplicated`

2020-03-17 16:29 UTC, jserv commented
Message "req pointer is for read only, recommend to remove redundant const specifier." was terrible because:
1. You should say, it is forbidden to assign read-only variable(s);
2. Check the dictionary about [recommend](https://www.merriam-webster.com/dictionary/recommend) for learning its usage.

2020-03-19 07:36 UTC, closed without merging

2020-03-19 08:05 UTC, jserv commented
Why did you close this pull request?

2020-03-19 08:11 UTC, splasky commented
Handle all same issue inside #52