Eliminate compilation warnings
DLTcollab/TA-endpoint pull request #52
Opened 2020-03-19 07:58 UTC by splasky

It is forbidden to assign read-only variables, remove redundant
const specifier.

Fix const qualifier warning and pointer signedness warning from
test_crypto_utils and main function. Inside test_crypto_utils.c we define
text test data as constant char* type, we should unify them.

Closes #51

2020-03-19 08:08 UTC, jserv commented
Fix grammar:
> It is forbidden to assign read-only variables, remove redundant
const specifier.

You need to explain the rationale between the two sentences.

2020-03-19 08:08 UTC, jserv commented
There should be only one git commit. Squash and rework.

2020-03-20 07:54 UTC, howjmay requested changes

2020-03-20 07:54 UTC, HowJMay commented on main.c
> +  char ciphertext[1024] = {0}, raw_msg[1000] = {0};
Declare these variables with line 91

2020-03-20 07:54 UTC, HowJMay commented on main.c
> +  uint8_t iv[16] = {0};
Use macro for IV size

2020-03-21 05:34 UTC, merged